---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-kube-spot
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-kube-spot-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: drone-kube-spot
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kube-spot
  namespace: kube-system
  labels:
    app: drone-kube-spot
spec:
  selector:
    matchLabels:
      app: drone-kube-spot
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drone-kube-spot
    spec:
      serviceAccountName: drone-kube-spot
      containers:
      - name:  drone-kube-spot
        image: ysicing/drone-kube-spot
        imagePullPolicy: Always
        env:
        - name: label
          value: "workload_type=spot"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always